# Generated by Django 5.2.5 on 2025-09-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_add_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voter',
            name='reg_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
